version: '3.8'

services:
  bank_of_russia_tg_bot:
    image: ${DOCKER_REGISTRY-}bankofrussiatgbot
    build:
      context: .
      dockerfile: Bank_of_Russia_tg_bot/Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped